### ISSUE TITLE
Issue when running mummer2circos on 3KB amplicon contigs

### ISSUE THREAD

**Issue by Rohit-Satyam** [metagenlab/mummer2circos#13]
Hi

I have had successful runs with mummer2circos but this time it fails with the following error:

```
Traceback (most recent call last):
  File "/home/subudhak/miniconda3/envs/mummercircos/bin/mummer2circos", line 10, in <module>
    sys.exit(main())
  File "/home/subudhak/miniconda3/envs/mummercircos/lib/python3.7/site-packages/mummer2circos/__init__.py", line 71, in main
    circosf.run_circos(out_prefix=args.output_name, config_file="circos_data/circos.config")
  File "/home/subudhak/miniconda3/envs/mummercircos/lib/python3.7/site-packages/mummer2circos/mummer2circos.py", line 727, in run_circos
    raise CircosException("Circos problem, check circos log file (circos.log and circos.err)... quitting")
mummer2circos.mummer2circos.CircosException: Circos problem, check circos log file (circos.log and circos.err)... quitting

```

My query is 3Kb long and my target is 8kb long if that helps. Also below are the log file contents:

`circos.log`
```
debuggroup summary 0.17s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002
debuggroup summary 0.18s current working directory /home/subudhak/Documents/xxxx/vp1_only_scrub/p1_region_bams_only/p1assemblies
debuggroup summary 0.18s command /home/subudhak/miniconda3/envs/mummercircos/bin/circos -outputfile nucmer2circos.svg -conf circos_data/circos.config
debuggroup summary 0.18s loading configuration from file circos_data/circos.config
debuggroup summary 0.18s found conf file circos_data/circos.config
debuggroup summary 0.32s debug will appear for these features: output,summary
debuggroup summary 0.32s bitmap output image ./nucmer2circos.png
debuggroup summary 0.32s SVG output image ./nucmer2circos.svg
debuggroup summary 0.32s HTML map file ./nucmer2circos.html
debuggroup summary 0.32s parsing karyotype and organizing ideograms
debuggroup summary 0.33s karyotype has 1 chromosomes of total size 8,135
debuggroup summary 0.33s applying global and local scaling
debuggroup summary 0.33s allocating image, colors and brushes
debuggroup summary 1.80s drawing 1 ideograms of total size 8,135
debuggroup summary 1.80s drawing highlights and ideograms
debuggroup summary 1.83s found conf file /home/subudhak/miniconda3/envs/mummercircos/bin/../etc/tracks/heatmap.conf
debuggroup summary 1.83s found conf file /home/subudhak/miniconda3/envs/mummercircos/bin/../etc/tracks/line.conf
debuggroup summary 1.84s found conf file /home/subudhak/miniconda3/envs/mummercircos/bin/../etc/tracks/line.conf
debuggroup summary 1.84s processing track_0 heatmap circos_data/temp.heat
debuggroup summary 1.84s processing track_1 line circos_data/circos_GC_skew.txt
debuggroup summary 1.84s processing track_2 line circos_data/circos_GC_var.txt
debuggroup summary 1.84s drawing track_0 heatmap z 1 temp.heat 
```

`circos.err`

```
Use of uninitialized value $plot_min in subtraction (-) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/
Circos/Heatmap.pm line 267, <F> line 16.
Use of uninitialized value $plot_max in subtraction (-) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/
Circos/Heatmap.pm line 267, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Cir
cos/Heatmap.pm line 272, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Cir
cos/Heatmap.pm line 273, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Cir
cos/Heatmap.pm line 272, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Cir
cos/Heatmap.pm line 273, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Cir
cos/Heatmap.pm line 272, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Cir
cos/Heatmap.pm line 273, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Cir
cos/Heatmap.pm line 272, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Cir
cos/Heatmap.pm line 273, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 272, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 273, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 272, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 273, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Cir

cos/Heatmap.pm line 273, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 272, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 273, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 272, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 273, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 272, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 273, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 272, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 273, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 272, <F> line 16.
Use of uninitialized value $plot_min in addition (+) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 273, <F> line 16.
Use of uninitialized value in subtraction (-) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 225, <F> line 16.
Use of uninitialized value in subtraction (-) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 225, <F> line 16.
Use of uninitialized value in subtraction (-) at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 225, <F> line 16.
Illegal division by zero at /home/subudhak/miniconda3/envs/mummercircos/bin/../lib/Circos/Heatmap.pm line 225, <F> line 16.

```

**Comment by tpillone** [comment]
Hi @Rohit-Satyam  

Are you sure that those two sequences share some similarity? 
What is the content of the file "circos_data/temp.heat"? If the two sequences do not overlap, the file "temp.heat" will be empty. 
If they are only remotely similar, you can try to align them with promer instead of nucmer (default option) with the option "-a promer".

Best

**Comment by Rohit-Satyam** [comment]
Hi @tpillone. Yes I am sure that these two sequences are similar. On one hand I have an ORF of a viral genome that we sequenced and on the other hand we have a genome of reference. Yes the **temp.heat** was empty. I wanted to see and show visually if there is inversion in the assembled region or not. To check if the assembled region has high similarity or not, I get over 80% of identity in BlastN. They assemble as a single contig as well.

I have a feature request too: When we don't use `-l` option, Mummer picks up a single contig/ sequence from both the files. Is it possible to make it pick all the contigs?

**Comment by tpillone** [comment]
Hi,
By default it should should keep alignments of at least 100bp with a minimum of 30% identity. Did you try the "-p promer" option?  
Would you mind sending me those files? 

As for your second question, it should already by the case as in the example below (simply running `mummer2circos -q <fasta1> -r <fasta2>`)
![nucmer2circos](https://github.com/metagenlab/mummer2circos/assets/33416812/6f60ed3c-317c-47f5-9f4c-0b5e46634ce7)
