### ISSUE TITLE
Error running example dataset

### ISSUE THREAD

**Issue by rajaldebnath** [metagenlab/mummer2circos#4]
Hi,
The program seems to fail with the example datasets provided in the repo. I did a conda installation with the yaml file running on MacOS

Please help troubleshoot it. 

`$mummer2circos -l -r genomes/NZ_CP008827.fna -q genomes/*.fna`

`nucmer -b 200 -c 65 -g 90 -l 20 -p CP006659 genomes/NZ_CP008827.fna genomes/CP006659.fna
Traceback (most recent call last):
  File "/Users/rajaldebnath/miniconda3/envs/mummer2circos/bin/mummer2circos", line 8, in <module>
    sys.exit(main())
  File "/Users/rajaldebnath/miniconda3/envs/mummer2circos/lib/python3.7/site-packages/mummer2circos/__init__.py", line 67, in main
    blast_identity_cutoff=args.blast_identity_cutoff)
  File "/Users/rajaldebnath/miniconda3/envs/mummer2circos/lib/python3.7/site-packages/mummer2circos/mummer2circos.py", line 71, in __init__
    nucmer_utility.execute_promer(fasta1, fasta2, algo="nucmer")
  File "/Users/rajaldebnath/miniconda3/envs/mummer2circos/lib/python3.7/site-packages/TPutils/nucmer_utility.py", line 41, in execute_promer
    raise Exception("%s" % b)
Exception: b'1: PREPARING DATA\n2,3: RUNNING mummer AND CREATING CLUSTERS\n# reading input file "CP006659.ntref" of length 5766619\n# construct suffix tree for sequence of length 5766619\n# (maximum reference length is 18446744073709551612)\n# (maximum query length is 18446744073709551615)\n# process 57666 characters per dot\n#....................................................................................................\n# CONSTRUCTIONTIME /Users/rajaldebnath/miniconda3/envs/mummer2circos/opt/mummer-3.23/mummer CP006659.ntref 2.46\n# reading input file "/Users/rajaldebnath/Software/mummer2circos/examples/genomes/CP006659.fna" of length 5781131\n# matching query-file "/Users/rajaldebnath/Software/mummer2circos/examples/genomes/CP006659.fna"\n# against subject-file "CP006659.ntref"\nERROR: mummer and/or mgaps returned non-zero\n'`

**Comment by tpillone** [comment]
Hi @rajaldebnath 

It's an error from nucmer, but it's not very detailed, it's difficult to say what could be the cause of the problem. The easiest way to avoid this problem would be to use the docker container instead of installing the conda environment. 

Do you also have an error if you use **promer** instead of **nucmer**? 

`mummer2circos -l -r genomes/NZ_CP008827.fna -q genomes/NZ_CP012745.fna -a promer`

You can also try to use **blast** instead of **mummer** using the following command, but you will need to upgrade mummer2circos first

```
# update mummer2circos
conda activate mummer2circos
pip install --upgrade --force-reinstall git+https://github.com/metagenlab/mummer2circos
# run with megablast
mummer2circos -l -r genomes/NZ_CP008827.fna -qmummer2circos -l -r genomes/NZ_CP008827.fna -q genomes/NZ_CP012745.fna -a megablast
```

**Comment by tpillone** [comment]
You can also try to update mummer to version 4

```
conda activate mummer2circos
# install mummer4
conda install -c bioconda mummer4
```

**Comment by rajaldebnath** [comment]
Thank you for your response. It works with nucmer and blast as an algorithm but does not generate the synteny plot with megablast. 
Also, I just wanted to know if mummer2circos can be used for eukaryotic synteny analysis.

`(mummer2circos) $ mummer2circos -r genomes/NZ_CP012745.fna -q genomes/*.fna -gb GCF_000281535_merged.gbk -b VF.faa -s GCF_000281535.depth -lf labels.txt -a megablast
Traceback (most recent call last):
  File "/home/ramesh/anaconda3/envs/mummer2circos/bin/mummer2circos", line 8, in <module>
    sys.exit(main())
  File "/home/ramesh/anaconda3/envs/mummer2circos/lib/python3.7/site-packages/mummer2circos/__init__.py", line 67, in main
    blast_identity_cutoff=args.blast_identity_cutoff)
  File "/home/ramesh/anaconda3/envs/mummer2circos/lib/python3.7/site-packages/mummer2circos/mummer2circos.py", line 80, in __init__
    hit_list, query_list = self.get_link("%s.coords" % outname, algo=algo)
  File "/home/ramesh/anaconda3/envs/mummer2circos/lib/python3.7/site-packages/mummer2circos/mummer2circos.py", line 1060, in get_link
    10 + shift]) + '\t' + l[2] + '\t' + l[3] + '\tcolor=%s' % color_id + '\n')
UnboundLocalError: local variable 'shift' referenced before assignment`
